name: Release

on:
  release:
    types:
      - published

jobs:
  float-major-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Float major version tag
        uses: ./
